In [1]:
import numpy as np

In [3]:
# 행렬 곱 연산
# 앞의 열과 뒤의 행이 같아야함! 결과는 앞의 행과 뒤의 열의 모양으로 나옴

arr1 = np.array([[1,2,3],[4,5,6]])  #(2,3)
arr2 = np.array([[4,5],[6,7],[8,9]]) #(3,2)
print(np.matmul(arr1,arr2))

[[ 40  46]
 [ 94 109]]


In [22]:
# 전치 행렬(transpose)
# 행을 열로 열을 행으로 바꿈

arr = np.array([[1,2,3],[4,5,6]])   #(2,3)
print(arr)    #[[1 2 3]
              # [4 5 6]]

print(arr.T)  #[[1 4] 
              # [2 5]
              # [3 6]]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# iterator (반복자)를 이용한 반복문 처리
# 보통 for문을 이용하는데, ndarray는 while문과 iterator를 이용해서 반복처리를 선호!
arr = np.array([1,2,3,4,5])

#for문 사용
for tmp in arr:
    print(tmp)
    
# iterator 사용
my_iter = np.nditer(arr, flags=['c_index'])

while not my_iter.finished:
    idx = my_iter.index
    print(arr[idx])
    my_iter.iternext()

1
2
3
4
5
1
2
3
4
5


In [11]:
# 2차원 ndarray에 반복처리
arr = np.array([[1,2,3],[4,5,6]])

for tmp1 in range(arr.shape[0]):
    for tmp2 in range(arr.shape[1]):
        print(arr[tmp1,tmp2])
        
my_iter = np.nditer(arr, flags=['multi_index'])
while not my_iter.finished:
    idx = my_iter.multi_index
    print(arr[idx])
    my_iter.iternext()

1
2
3
4
5
6
1
2
3
4
5
6


for문은 차원수가 늘어날수록 중첩되는 for문의 수도 늘어남
근데, iterator는 multi_index로 다차원 배열은 모두 해결 가능!

In [16]:
# 다양한 집계함수

arr = np.arange(1,7,1).reshape(2,3)
print(arr)     #[[1 2 3]
               # [4 5 6]]
    
# ndarray 데이터에 대한 합을 구할 수 있음
print(np.sum(arr))  # 21 => Numpy가 제공하는 함수를 이용
print(arr.sum())    # 21 => ndarray가 가지고 있는 메소드 이용
print(arr.mean())   # 3.5
print(arr.max())    # 6
print(arr.min())    # 1
print(arr.argmax()) # 5 => 가장 큰값의 index값
print(arr.std())    # 표준편차

[[1 2 3]
 [4 5 6]]
21
21
3.5
6
1
5
1.707825127659933


In [17]:
# axis개념
arr = np.arange(1,7,1).reshape(2,3)
print(arr)     #[[1 2 3]
               # [4 5 6]]

# 2차원에서 axis가 0이면 행방향, 1이면 열방향
print(arr.sum(axis=0))    #[5 7 9]
print(arr.sum(axis=1))    #[ 6 15]


[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [21]:
# 연습문제!

arr = np.arange(1,17,1).reshape(4,4)
print(arr)

# 이 안에 10보다 큰 수는 몇개 있나요?
# boolean indexing 사용
my_mask = (arr > 10)
print(my_mask.sum())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6


In [ ]:
# ndarray 정렬, 연결, 삭제, CSV파일 로딩은 pandas로 처리