In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:/jupyter_home/data/student_scores_em.csv',
                 index_col='student number')
en_scores = df['english'][:10]
ma_scores = df['mathematics'][:10]

scores_df= pd.DataFrame({'english':en_scores.values,
                         'mathematics':ma_scores.values},
                        index=['A','B','C','D','E','F','G','H','I','J'])
display(scores_df)

english  mathematics
A       42           65
B       69           80
C       56           63
D       41           63
E       57           76
F       48           60
G       65           81
H       49           66
I       65           78
J       58           82

In [6]:
# 공분산 이어서 
scores_df ['en_deviation'] = scores_df['english'] - scores_df['english'].mean()
scores_df ['ma_deviation'] = scores_df['mathematics'] - scores_df['mathematics'].mean()
scores_df ['product_deviation'] = scores_df['en_deviation'] * scores_df['ma_deviation']
display(scores_df)

print('covariance(공분산) : ',scores_df['product_deviation'].mean()) # 62.8 => 양수이므로 양의 상관관계에 있음

english  mathematics  en_deviation  ma_deviation  product_deviation
A       42           65         -13.0          -6.4               83.2
B       69           80          14.0           8.6              120.4
C       56           63           1.0          -8.4               -8.4
D       41           63         -14.0          -8.4              117.6
E       57           76           2.0           4.6                9.2
F       48           60          -7.0         -11.4               79.8
G       65           81          10.0           9.6               96.0
H       49           66          -6.0          -5.4               32.4
I       65           78          10.0           6.6               66.0
J       58           82           3.0          10.6               31.8

covariance(공분산) :  62.8


In [11]:
# 공분산(numpy로 구하기)
df = pd.read_csv('C:/jupyter_home/data/student_scores_em.csv',
                 index_col='student number')
en_scores = df['english'][:10]
ma_scores = df['mathematics'][:10]

scores_df= pd.DataFrame({'english':en_scores.values,
                         'mathematics':ma_scores.values},
                        index=['A','B','C','D','E','F','G','H','I','J'])

# numpy 함수 이용 => 결과가 공분산 행렬로 리턴
# 기본값으로 불편분산을 사용, 표본분산을 알고 싶으면 ddof옵션을 걸어줘야함(0=표본,1=불편)
cov_matrix = np.cov(en_scores, ma_scores, ddof=0)
print(cov_matrix)
# (0,0) = 영어와 영어의 공분산 => 영어의 공분산
# (0,1) = 영어와 수학의 공분산 
# (1,0) = 수학과 영어의 공분산 
# (1,1) = 수학과 수학의 공분산 => 수학의 공분산

[[86.   62.8 ]
 [62.8  68.44]]


pandas에도 공분산이 있음, pandas는 무조건 불편분산만 가능

In [3]:
# 실제 데이터로 공분산 구하기
# kospi 지수와 삼성전자 주가에 대한 공분산을 구하기
# 2018년 기준 코스피 200안에 삼전이 차지하는 비율은 33%

# yahoo finance 사이트에서 주가데이터 받아서 사용할거임
import pandas_datareader.data as pdr
# 설치해야함 pip install pandas_datareader
from datetime import datetime

start = datetime(2018,1,1) # 특정날짜에 대한 날짜객체 생성
print(start)  # 2018-01-01 00:00:00
end = datetime(2018,12,31)

df_kospi = pdr.DataReader('^KS11','yahoo',start,end)
display(df_kospi.head())

df_se = pdr.DataReader('005930.KS','yahoo',start,end)
display(df_se.head())

2018-01-01 00:00:00


High          Low         Open        Close  Volume  \
Date                                                                     
2018-01-02  2481.020020  2465.939941  2474.860107  2479.649902  262200   
2018-01-03  2493.399902  2481.909912  2484.629883  2486.350098  331100   
2018-01-04  2502.500000  2466.449951  2502.500000  2466.459961  333800   
2018-01-05  2497.520020  2475.510010  2476.850098  2497.520020  308800   
2018-01-08  2515.370117  2494.179932  2510.699951  2513.280029  311400   

              Adj Close  
Date                     
2018-01-02  2479.649902  
2018-01-03  2486.350098  
2018-01-04  2466.459961  
2018-01-05  2497.520020  
2018-01-08  2513.280029

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2018-01-02  51400.0  50780.0  51380.0  51020.0   8474250.0  45077.808594
2018-01-03  52560.0  51420.0  52540.0  51620.0  10013500.0  45607.921875
2018-01-04  52180.0  50640.0  52120.0  51080.0  11695450.0  45130.812500
2018-01-05  52120.0  51200.0  51300.0  52120.0   9481150.0  46049.675781
2018-01-08  52520.0  51500.0  52400.0  52020.0   8383650.0  45961.332031

In [18]:
cov_matrix = np.cov(df_kospi['Close'],df_se['Close'],ddof=0)
print(cov_matrix)  # 양의 상관관계

[[   24078.14439225   488212.99831291]
 [  488212.99831291 11871059.41111261]]


In [19]:
# 다른종목 공분산 구하기
# 남북경험주=부산 방산주=lig
df_busan= pdr.DataReader('011390.KS','yahoo',start,end)
df_lig = pdr.DataReader('079550.KS','yahoo',start,end)

cov_matrix = np.cov(df_busan['Close'],df_lig['Close'],ddof=0)
print(cov_matrix) # 음의 상관관계

[[ 4.62857448e+09 -3.84951773e+08]
 [-3.84951773e+08  6.33317924e+07]]


In [20]:
# 상관계수 구하기 (코스피와 삼전)
corr_coef = np.corrcoef(df_kospi['Close'],df_se['Close'])
print(corr_coef)

[[1.         0.91317306]
 [0.91317306 1.        ]]
