In [3]:
# logistic regression으로 gate연산을 학습할 수 있는지 확인
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings(action='ignore')

ERROR! Session/line number was not unique in database. History logging moved to new session 66


### And gate

In [4]:
# training data set
x_data = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]], dtype=np.float64)

# and gate 연산에 대한 t_data
t_data = np.array([0,0,0,1], dtype=np.float64)

In [5]:
# placeholder
X = tf.placeholder(shape=[None,2], dtype=tf.float32)
T = tf.placeholder(shape=[None,1], dtype=tf.float32)

# weight & bias
W = tf.Variable(tf.random.normal([2,1]))
b = tf.Variable(tf.random.normal([1]))

# Hypothesis, model
logit = tf.matmul(X,W) + b
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                             labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# session,초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 반복학습
for step in range(30000):
    _, loss_val = sess.run([train, loss],
                          feed_dict={X:x_data,T:t_data.reshape(-1,1)})
    if step % 3000 ==0:
        print('loss_value:',loss_val)

ERROR! Session/line number was not unique in database. History logging moved to new session 67



loss_value: 2.1837347
loss_value: 0.33547285
loss_value: 0.2142832
loss_value: 0.16050106
loss_value: 0.12838848
loss_value: 0.10681925
loss_value: 0.09131375
loss_value: 0.07963886
loss_value: 0.07054174
loss_value: 0.06326138


In [6]:
# evaluation(모델평가)
predict = tf.cast(H >= 0.5, dtype=tf.float32)
predict_val = sess.run(predict, feed_dict={X:x_data})
print(predict_val)

print(classification_report(t_data, predict_val.ravel()))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지 확인

[[0.]
 [0.]
 [0.]
 [1.]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         3
         1.0       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



### or gate

In [7]:
# or gate 연산에 대한 t_data
t_data = np.array([0,1,1,1], dtype=np.float64)

# placeholder
X = tf.placeholder(shape=[None,2], dtype=tf.float32)
T = tf.placeholder(shape=[None,1], dtype=tf.float32)

# weight & bias
W = tf.Variable(tf.random.normal([2,1]))
b = tf.Variable(tf.random.normal([1]))

# Hypothesis, model
logit = tf.matmul(X,W) + b
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                             labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# session,초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 반복학습
for step in range(30000):
    _, loss_val = sess.run([train, loss],
                          feed_dict={X:x_data,T:t_data.reshape(-1,1)})
    if step % 3000 ==0:
        print('loss_value:',loss_val)

ERROR! Session/line number was not unique in database. History logging moved to new session 68
loss_value: 0.48401988
loss_value: 0.21451785
loss_value: 0.13562524
loss_value: 0.09783657
loss_value: 0.075964995
loss_value: 0.061828632
loss_value: 0.05199617
loss_value: 0.044788335
loss_value: 0.039291747
loss_value: 0.034969162


In [8]:
# evaluation(모델평가)
predict = tf.cast(H >= 0.5, dtype=tf.float32)
predict_val = sess.run(predict, feed_dict={X:x_data})
print(predict_val)

print(classification_report(t_data, predict_val.ravel()))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지

[[0.]
 [1.]
 [1.]
 [1.]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         1
         1.0       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



### dnn으로 xor gate

In [9]:
# xor gate 연산에 대한 t_data
t_data = np.array([0,1,1,0], dtype=np.float64)

# placeholder
X = tf.placeholder(shape=[None,2], dtype=tf.float32)
T = tf.placeholder(shape=[None,1], dtype=tf.float32)

# weight & bias
W2 = tf.Variable(tf.random.normal([2,10]))
b2 = tf.Variable(tf.random.normal([10]))
layer2 = tf.sigmoid(tf.matmul(X,W2) + b2)

W3 = tf.Variable(tf.random.normal([10,6]))
b3 = tf.Variable(tf.random.normal([6]))
layer3 = tf.sigmoid(tf.matmul(layer2,W3) + b3)

W4 = tf.Variable(tf.random.normal([6,1]))
b4 = tf.Variable(tf.random.normal([1]))

# Hypothesis, model
logit = tf.matmul(layer3,W4) + b4
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                             labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# session,초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 반복학습
for step in range(30000):
    _, loss_val = sess.run([train, loss],
                          feed_dict={X:x_data,T:t_data.reshape(-1,1)})
    if step % 3000 ==0:
        print('loss_value:',loss_val)

loss_value: 0.8676406
loss_value: 0.63742626
loss_value: 0.5071445
loss_value: 0.33603504
loss_value: 0.19674474
loss_value: 0.12460972
loss_value: 0.087880164
loss_value: 0.0667858
loss_value: 0.05337303
loss_value: 0.04418888


In [10]:
# evaluation(모델평가)
predict = tf.cast(H >= 0.5, dtype=tf.float32)
predict_val = sess.run(predict, feed_dict={X:x_data})
print(predict_val)

print(classification_report(t_data, predict_val.ravel()))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지

[[0.]
 [1.]
 [1.]
 [0.]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         2
         1.0       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [3]:
# tensorflow 2.x 버전으로 구현

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD
from sklearn.metrics import classification_report

In [5]:
print(tf.__version__)

2.3.0


In [9]:
# training data set
x_data = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]], dtype=np.float64)

# xor gate 연산에 대한 t_data
t_data = np.array([0,1,1,0], dtype=np.float64)

# tensorflow 구현
model = Sequential()

model.add(Flatten(input_shape=(2,))) # input layer
model.add(Dense(units=128, activation='sigmoid')) # 1번째 hidden layer
model.add(Dense(units=64, activation='sigmoid')) # 2번째 hidden layer
model.add(Dense(units=32, activation='sigmoid'))
model.add(Dense(units=1, activation='sigmoid')) # output layer

model.compile(optimizer=SGD(learning_rate=1e-4),
             loss='binary_crossentropy')

model.fit(x_data,t_data.reshape(-1,1),
         epochs=30000,
         verbose=0)

In [11]:
# evaluation(모델평가)
predict_val = model.predict(x_data)
predict_val = tf.cast(predict_val > 0.5, dtype=tf.float32).numpy().ravel()
print(predict_val)

print(classification_report(t_data, predict_val))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지

[0. 0. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.50      0.50      0.50         2
         1.0       0.50      0.50      0.50         2

    accuracy                           0.50         4
   macro avg       0.50      0.50      0.50         4
weighted avg       0.50      0.50      0.50         4

